[package]
name = "zpr"
version = "0.8.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp = { version = "0.25", optional = true }
open-enum = { version = "0.5" }
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "1.0.65"
url = "2.5.4"

[build-dependencies]
capnpc = "0.25"

[features]
policy = ["capnp"]
vsapi = ["capnp"]
all = ["policy", "vsapi"]
