[package]
name = "zpr"
version = "0.2.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp = "0.23"
open-enum = { version = "0.5" }
strum = { version = "0.26", features = ["derive"] }
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "1.0.65"
vsapi = { git = "https://github.com/org-zpr/zpr-vsapi-rs.git", tag = "v0.4.1" }
url = "2.5.4"

[build-dependencies]
capnpc = "0.23"
