[package]
name = "zpr"
version = "0.5.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
capnp = { version = "0.23", optional = true }
open-enum = { version = "0.5" }
zerocopy = { version = "0.8", features = ["derive"] }
thiserror = "1.0.65"
vsapi = { git = "https://github.com/org-zpr/zpr-vsapi-rs.git", tag = "v0.4.1", optional = true }
url = "2.5.4"

[build-dependencies]
capnpc = "0.23"

[features]
policy = ["capnp"]
vsapi = ["capnp", "dep:vsapi"]
all = ["policy", "vsapi"]
